Ms2 add remove book
Bishoy-Samwel/bookstore-1 pull request #2
Opened 2021-11-02 15:15 UTC by Bishoy-Samwel

- [ ] Configure the Redux Store and importing the necessary methods from Redux
 *  Import createStore
*  Import combineReducers 
*  Import applyMiddleware 
*  Import your booksReducer,
- [ ]  Write your book's actions and reducer using the ducks pattern. <https://github.com/erikras/ducks-modular-redux>
*  Define action types:
*  Set initial stateto be an empty array of books
*  Export your Action Creators (functions, which return actions):
*  Write your reducer and export it as default

- [ ] In your React component responsible for adding new books set the data inputs in the local React state (set title and author ). Once your new book object is ready to be submitted to Redux store, dispatch a corresponding action
- [ ] In your React component responsible for removing books - implement that even by dispatching a corresponding action.

2021-11-02 15:48 UTC, Emmyn5600 requested changes
Hi, @Bishoy-Samwel 

Good job so far! 👏🏼 
Great work on making the project requirements :clap:
You've done well-implementing project requirements, but there are still some issues which aren't been addressed yet 
 
## STATUS: CHANGES REQUESTED :recycle:


### Changes requested.

- [x] Check the comment under the review.

 #### Optional suggestions
 
 - N/A
 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-11-02 15:48 UTC, Emmyn5600 commented on src/components/AddBookForm.js
> +import { addBook } from '../redux/books/books';
- [ ] I had an issue while trying to run the project locally. Please fix it.
![uuid](https://user-images.githubusercontent.com/55635977/139880242-186d85ee-8c3f-49b0-b2e6-aee2b66f3a1a.png)

2021-11-02 15:48 UTC, Emmyn5600 commented on src/components/Book.js
> +export default function Book(props) {
- [ ] kindly use ES6 syntax. and make sure that you changed all you used the `function` to const as well as the arrow function.

2021-11-02 15:48 UTC, Emmyn5600 commented on src/redux/books/books.js
> +});
- [ ] Let us create the actions before anything and call the actions created in the reducers, refer to the below example.

const ADD_BOOK = 'bookStore/books/ADD_BOOK';
const REMOVE_BOOK = 'bookStore/books/REMOVE_BOOK';

const initialState = [];

export const addBook = (payload) => ({
  type: ADD_BOOK,
  payload,
});

export const removeBook = (payload) => ({
  type: REMOVE_BOOK,
  payload,
});

const reducer = (state = initialState, action) => {
  switch (action.type) {
    case ADD_BOOK:
      return [...state, action.payload];
    case REMOVE_BOOK:
      return state.filter((book) => book.id !== action.payload.id);

    default:
      return state;
  }
};

export default reducer;

2021-11-03 09:21 UTC, dasileker approved these changes
## **Hi @Bishoy-Samwel** 

### **Optional**

- Please make sure to update the readme file, before sending the **_PR_** for review.

## **Congratulations! 🎉 Project Approved ✅**
Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 

![Approved](https://user-images.githubusercontent.com/61562626/140035201-9a4ed5ca-7f03-41d5-9422-70efd9bfd6ba.gif)

 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-03 10:30 UTC, merged